### ISSUE TITLE
Problems with Taffy on CF

### ISSUE THREAD

**Issue by asosahn** [atuttle/Taffy#313]
the taffy was working ok and some day broken down. I don't know if was a java update.

the error:

```
ERROR WHEN LOGGING EXCEPTION - struct

Detail: [empty string]
ErrNumber: 0
Message: Element _TAFFY.SETTINGS.EXCEPTIONLOGADAPTER is undefined in APPLICATION.
Resolvedname: APPLICATION
StackTrace: coldfusion.runtime.UndefinedElementException: Element _TAFFY.SETTINGS.EXCEPTIONLOGADAPTER is undefined in APPLICATION.
    at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1808)
        at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1726)
        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1875)
        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
        at cfapi2ecfc1033718934$funcONERROR.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:135)
        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
        at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
        at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
        at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
        at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
        at coldfusion.runtime.AppEventInvoker.onError(AppEventInvoker.java:491)
        at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:532)
        at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
        at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
        at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
        at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
        at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
        at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
        at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
        at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
        at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
        at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
        at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
        at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
        at coldfusion.CfmServlet.service(CfmServlet.java:219)
        at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
        at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
        at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:422)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:199)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:744)
        Suppressed:
    [array]
    TagContext:
    [array]
        1) [struct]
            COLUMN: 0
                ID: ??
                LINE: 135
                RAW_TRACE: at cfapi2ecfc1033718934$funcONERROR.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:135)
                TEMPLATE: /Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc
                TYPE: CFML 
                Type: Expression
        element: _TAFFY.SETTINGS.EXCEPTIONLOGADAPTER
objectType:
    [object of java.lang.Class]
        Class Name: java.lang.Class
        Methods:
            asSubclass(java.lang.Class) returns java.lang.Class 
                    cast(java.lang.Object) returns java.lang.Object 
                desiredAssertionStatus() returns boolean 
                forName(java.lang.String, boolean, java.lang.ClassLoader) returns java.lang.Class 
                forName(java.lang.String) returns java.lang.Class 
                getAnnotation(java.lang.Class) returns java.lang.annotation.Annotation 
                getAnnotations() returns java.lang.annotation.Annotation[] 
                getCanonicalName() returns java.lang.String 
                getClassLoader() returns java.lang.ClassLoader 
                getClasses() returns java.lang.Class[] 
                getComponentType() returns java.lang.Class 
                getConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                getConstructors() returns java.lang.reflect.Constructor[] 
                getDeclaredAnnotations() returns java.lang.annotation.Annotation[] 
                getDeclaredClasses() returns java.lang.Class[] 
                getDeclaredConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                getDeclaredConstructors() returns java.lang.reflect.Constructor[] 
                getDeclaredField(java.lang.String) returns java.lang.reflect.Field 
                getDeclaredFields() returns java.lang.reflect.Field[] 
                getDeclaredMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                getDeclaredMethods() returns java.lang.reflect.Method[] 
                getDeclaringClass() returns java.lang.Class 
                getEnclosingClass() returns java.lang.Class 
                getEnclosingConstructor() returns java.lang.reflect.Constructor 
                getEnclosingMethod() returns java.lang.reflect.Method 
                getEnumConstants() returns java.lang.Object[] 
                getField(java.lang.String) returns java.lang.reflect.Field 
                getFields() returns java.lang.reflect.Field[] 
                getGenericInterfaces() returns java.lang.reflect.Type[] 
                getGenericSuperclass() returns java.lang.reflect.Type 
                getInterfaces() returns java.lang.Class[] 
                getMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                getMethods() returns java.lang.reflect.Method[] 
                getModifiers() returns int 
                getName() returns java.lang.String 
                getPackage() returns java.lang.Package 
                getProtectionDomain() returns java.security.ProtectionDomain 
                getResource(java.lang.String) returns java.net.URL 
                getResourceAsStream(java.lang.String) returns java.io.InputStream 
                getSigners() returns java.lang.Object[] 
                getSimpleName() returns java.lang.String 
                getSuperclass() returns java.lang.Class 
                getTypeParameters() returns java.lang.reflect.TypeVariable[] 
                isAnnotation() returns boolean 
                isAnnotationPresent(java.lang.Class) returns boolean 
                isAnonymousClass() returns boolean 
                isArray() returns boolean 
                isAssignableFrom(java.lang.Class) returns boolean 
                isEnum() returns boolean 
                isInstance(java.lang.Object) returns boolean 
                isInterface() returns boolean 
                isLocalClass() returns boolean 
                isMemberClass() returns boolean 
                isPrimitive() returns boolean 
                isSynthetic() returns boolean 
                newInstance() returns java.lang.Object 
                toString() returns java.lang.String

ORIGINAL EXCEPTION - struct
        Cause:
    [struct]
        Detail: [empty string]
        ErrNumber: 0
        Message: Element _TAFFY.SETTINGS.RELOADKEY is undefined in APPLICATION.
        Resolvedname: APPLICATION
        StackTrace: coldfusion.runtime.UndefinedElementException: Element _TAFFY.SETTINGS.RELOADKEY is undefined in APPLICATION.
            at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1808)
                at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1726)
                at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1875)
                at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
                at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
                at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
                at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
                at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
                at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
                at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
                at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
                at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
                at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:455)
                at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
                at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
                at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
                at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
                at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
                at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
                at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
                at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
                at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
                at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
                at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
                at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
                at coldfusion.CfmServlet.service(CfmServlet.java:219)
                at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
                at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
                at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:422)
                at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:199)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
                at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:744)
            Suppressed:
            [array]
                TagContext:
            [array]
                    1) [struct]
                    COLUMN: 0
                        ID: ??
                        LINE: 79
                        RAW_TRACE: at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
                        TEMPLATE: /Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc
                        TYPE: CFML 
                Type: Expression
        element: _TAFFY.SETTINGS.RELOADKEY
        objectType:
            [object of java.lang.Class]
                    Class Name: java.lang.Class
                Methods:
                    asSubclass(java.lang.Class) returns java.lang.Class 
                                cast(java.lang.Object) returns java.lang.Object 
                        desiredAssertionStatus() returns boolean 
                        forName(java.lang.String, boolean, java.lang.ClassLoader) returns java.lang.Class 
                        forName(java.lang.String) returns java.lang.Class 
                        getAnnotation(java.lang.Class) returns java.lang.annotation.Annotation 
                        getAnnotations() returns java.lang.annotation.Annotation[] 
                        getCanonicalName() returns java.lang.String 
                        getClassLoader() returns java.lang.ClassLoader 
                        getClasses() returns java.lang.Class[] 
                        getComponentType() returns java.lang.Class 
                        getConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                        getConstructors() returns java.lang.reflect.Constructor[] 
                        getDeclaredAnnotations() returns java.lang.annotation.Annotation[] 
                        getDeclaredClasses() returns java.lang.Class[] 
                        getDeclaredConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                        getDeclaredConstructors() returns java.lang.reflect.Constructor[] 
                        getDeclaredField(java.lang.String) returns java.lang.reflect.Field 
                        getDeclaredFields() returns java.lang.reflect.Field[] 
                        getDeclaredMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                        getDeclaredMethods() returns java.lang.reflect.Method[] 
                        getDeclaringClass() returns java.lang.Class 
                        getEnclosingClass() returns java.lang.Class 
                        getEnclosingConstructor() returns java.lang.reflect.Constructor 
                        getEnclosingMethod() returns java.lang.reflect.Method 
                        getEnumConstants() returns java.lang.Object[] 
                        getField(java.lang.String) returns java.lang.reflect.Field 
                        getFields() returns java.lang.reflect.Field[] 
                        getGenericInterfaces() returns java.lang.reflect.Type[] 
                        getGenericSuperclass() returns java.lang.reflect.Type 
                        getInterfaces() returns java.lang.Class[] 
                        getMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                        getMethods() returns java.lang.reflect.Method[] 
                        getModifiers() returns int 
                        getName() returns java.lang.String 
                        getPackage() returns java.lang.Package 
                        getProtectionDomain() returns java.security.ProtectionDomain 
                        getResource(java.lang.String) returns java.net.URL 
                        getResourceAsStream(java.lang.String) returns java.io.InputStream 
                        getSigners() returns java.lang.Object[] 
                        getSimpleName() returns java.lang.String 
                        getSuperclass() returns java.lang.Class 
                        getTypeParameters() returns java.lang.reflect.TypeVariable[] 
                        isAnnotation() returns boolean 
                        isAnnotationPresent(java.lang.Class) returns boolean 
                        isAnonymousClass() returns boolean 
                        isArray() returns boolean 
                        isAssignableFrom(java.lang.Class) returns boolean 
                        isEnum() returns boolean 
                        isInstance(java.lang.Object) returns boolean 
                        isInterface() returns boolean 
                        isLocalClass() returns boolean 
                        isMemberClass() returns boolean 
                        isPrimitive() returns boolean 
                        isSynthetic() returns boolean 
                        newInstance() returns java.lang.Object 
                        toString() returns java.lang.String
            Detail: An exception occurred while invoking an event handler method from Application.cfc. The method name is: onRequestStart.
            Message: Event handler exception.
            RootCause:
    [struct]
        Detail: [empty string]
        ErrNumber: 0
        Message: Element _TAFFY.SETTINGS.RELOADKEY is undefined in APPLICATION.
        Resolvedname: APPLICATION
        StackTrace: coldfusion.runtime.UndefinedElementException: Element _TAFFY.SETTINGS.RELOADKEY is undefined in APPLICATION.
            at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1808)
                at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1726)
                at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1875)
                at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
                at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
                at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
                at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
                at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
                at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
                at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
                at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
                at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
                at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
                at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:455)
                at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
                at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
                at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
                at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
                at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
                at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
                at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
                at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
                at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
                at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
                at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
                at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
                at coldfusion.CfmServlet.service(CfmServlet.java:219)
                at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
                at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
                at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:422)
                at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:199)
                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
                at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:744)
            Suppressed:
            [array]
                TagContext:
            [array]
                    1) [struct]
                    COLUMN: 0
                        ID: ??
                        LINE: 79
                        RAW_TRACE: at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
                        TEMPLATE: /Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc
                        TYPE: CFML 
                Type: Expression
        element: _TAFFY.SETTINGS.RELOADKEY
        objectType:
            [object of java.lang.Class]
                    Class Name: java.lang.Class
                Methods:
                    asSubclass(java.lang.Class) returns java.lang.Class 
                                cast(java.lang.Object) returns java.lang.Object 
                        desiredAssertionStatus() returns boolean 
                        forName(java.lang.String, boolean, java.lang.ClassLoader) returns java.lang.Class 
                        forName(java.lang.String) returns java.lang.Class 
                        getAnnotation(java.lang.Class) returns java.lang.annotation.Annotation 
                        getAnnotations() returns java.lang.annotation.Annotation[] 
                        getCanonicalName() returns java.lang.String 
                        getClassLoader() returns java.lang.ClassLoader 
                        getClasses() returns java.lang.Class[] 
                        getComponentType() returns java.lang.Class 
                        getConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                        getConstructors() returns java.lang.reflect.Constructor[] 
                        getDeclaredAnnotations() returns java.lang.annotation.Annotation[] 
                        getDeclaredClasses() returns java.lang.Class[] 
                        getDeclaredConstructor(java.lang.Class[]) returns java.lang.reflect.Constructor 
                        getDeclaredConstructors() returns java.lang.reflect.Constructor[] 
                        getDeclaredField(java.lang.String) returns java.lang.reflect.Field 
                        getDeclaredFields() returns java.lang.reflect.Field[] 
                        getDeclaredMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                        getDeclaredMethods() returns java.lang.reflect.Method[] 
                        getDeclaringClass() returns java.lang.Class 
                        getEnclosingClass() returns java.lang.Class 
                        getEnclosingConstructor() returns java.lang.reflect.Constructor 
                        getEnclosingMethod() returns java.lang.reflect.Method 
                        getEnumConstants() returns java.lang.Object[] 
                        getField(java.lang.String) returns java.lang.reflect.Field 
                        getFields() returns java.lang.reflect.Field[] 
                        getGenericInterfaces() returns java.lang.reflect.Type[] 
                        getGenericSuperclass() returns java.lang.reflect.Type 
                        getInterfaces() returns java.lang.Class[] 
                        getMethod(java.lang.String, java.lang.Class[]) returns java.lang.reflect.Method 
                        getMethods() returns java.lang.reflect.Method[] 
                        getModifiers() returns int 
                        getName() returns java.lang.String 
                        getPackage() returns java.lang.Package 
                        getProtectionDomain() returns java.security.ProtectionDomain 
                        getResource(java.lang.String) returns java.net.URL 
                        getResourceAsStream(java.lang.String) returns java.io.InputStream 
                        getSigners() returns java.lang.Object[] 
                        getSimpleName() returns java.lang.String 
                        getSuperclass() returns java.lang.Class 
                        getTypeParameters() returns java.lang.reflect.TypeVariable[] 
                        isAnnotation() returns boolean 
                        isAnnotationPresent(java.lang.Class) returns boolean 
                        isAnonymousClass() returns boolean 
                        isArray() returns boolean 
                        isAssignableFrom(java.lang.Class) returns boolean 
                        isEnum() returns boolean 
                        isInstance(java.lang.Object) returns boolean 
                        isInterface() returns boolean 
                        isLocalClass() returns boolean 
                        isMemberClass() returns boolean 
                        isPrimitive() returns boolean 
                        isSynthetic() returns boolean 
                        newInstance() returns java.lang.Object 
                        toString() returns java.lang.String
            StackTrace: coldfusion.runtime.EventHandlerException: Event handler exception.
                at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:287)
        at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:455)
        at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:42)
        at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
        at coldfusion.filter.PathFilter.invoke(PathFilter.java:142)
        at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
        at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
        at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
        at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
        at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
        at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:58)
        at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
        at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
        at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
        at coldfusion.CfmServlet.service(CfmServlet.java:219)
        at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
        at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at coldfusion.inspect.weinre.MobileDeviceDomInspectionFilter.doFilter(MobileDeviceDomInspectionFilter.java:121)
        at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:422)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:199)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:744)
        Caused by: coldfusion.runtime.UndefinedElementException: Element _TAFFY.SETTINGS.RELOADKEY is undefined in APPLICATION.
    at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1808)
        at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1726)
        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1875)
        at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
        at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:487)
        at coldfusion.runtime.UDFMethod$ArgumentCollectionFilter.invoke(UDFMethod.java:383)
        at coldfusion.filter.FunctionAccessFilter.invoke(FunctionAccessFilter.java:95)
        at coldfusion.runtime.UDFMethod.runFilterChain(UDFMethod.java:334)
        at coldfusion.runtime.UDFMethod.invoke(UDFMethod.java:231)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:643)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:432)
        at coldfusion.runtime.TemplateProxy.invoke(TemplateProxy.java:402)
        at coldfusion.runtime.AppEventInvoker.invoke(AppEventInvoker.java:108)
        at coldfusion.runtime.AppEventInvoker.onRequestStart(AppEventInvoker.java:279)
        ... 39 more
        Suppressed:
    [array]
    TagContext:
    [array]
        1) [struct]
            COLUMN: 0
                ID: ??
                LINE: 79
                RAW_TRACE: at cfapi2ecfc1033718934$funcONREQUESTSTART.runFunction(/Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc:79)
                TEMPLATE: /Applications/ColdFusion11/cfusion/wwwroot/Taffy/core/api.cfc
                TYPE: CFML 
                Type: Expression
        name: onRequestStart
```

**Comment by atuttle** [comment]
Did you try restarting CF? This could be a lot of things, but usually points to an error in your code during initialization.

**Comment by adrianramirezh90** [comment]
I have the same problem. I restarted de CF Application Server, I tried everything but still fail.
